services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
      JWT_SECRET: super-secret-key-for-development-only
      SUPER_USER_EMAIL: advisor@example.com
      SUPER_USER_PASSWORD: strongpassword123
      PORT: 3333
    ports:
      - "3333:3333"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3333
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333/
      INTERNAL_API_URL: http://backend:3333
    restart: unless-stopped

volumes:
  pg_data:

